"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        if key and key not in os.environ:
            os.environ[key] = value


_load_env_file(BASE_DIR / ".env")
_load_env_file(BASE_DIR / ".env.local")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-tpv!-0fd$4(yd1nvxt5!t%4r3ou*76wy=d(+7$q73xcx1ayt%%",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "false").strip().lower() == "true"

def _split_csv_env(name, default_values):
    raw = os.getenv(name, "").strip()
    if not raw:
        return default_values
    return [item.strip() for item in raw.split(",") if item.strip()]


def _first_non_empty(*values):
    for value in values:
        if value is None:
            continue
        text = str(value).strip()
        if (text.startswith('"') and text.endswith('"')) or (text.startswith("'") and text.endswith("'")):
            text = text[1:-1].strip()
        if text:
            return text
    return ""


def _parse_postgres_url(database_url):
    if not database_url:
        return {}

    parsed = urlparse(database_url)
    if (parsed.scheme or "").lower() not in {"postgres", "postgresql"}:
        return {}

    query = parse_qs(parsed.query or "")
    sslmode = _first_non_empty(*(query.get("sslmode") or []))
    connect_timeout = _first_non_empty(*(query.get("connect_timeout") or []))
    channel_binding = _first_non_empty(*(query.get("channel_binding") or []))

    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote((parsed.path or "").lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }

    if sslmode:
        config["SSLMODE"] = sslmode
    if connect_timeout:
        config["CONNECT_TIMEOUT"] = connect_timeout
    if channel_binding:
        config["CHANNEL_BINDING"] = channel_binding

    return config


def _build_database_settings():
    database_url = _first_non_empty(
        os.getenv("DATABASE_URL"),
        os.getenv("POSTGRES_URL"),
        os.getenv("POSTGRES_PRISMA_URL"),
        os.getenv("DATABASE_URL_UNPOOLED"),
        os.getenv("POSTGRES_URL_NON_POOLING"),
    )
    parsed_url = _parse_postgres_url(database_url)

    has_postgres_hint = bool(
        _first_non_empty(
            database_url,
            os.getenv("DB_HOST"),
            os.getenv("POSTGRES_HOST"),
            os.getenv("PGHOST"),
            os.getenv("PGHOST_UNPOOLED"),
            os.getenv("DB_NAME"),
            os.getenv("POSTGRES_DATABASE"),
            os.getenv("PGDATABASE"),
        )
    )

    engine = _first_non_empty(
        parsed_url.get("ENGINE"),
        os.getenv("DB_ENGINE"),
        "django.db.backends.postgresql" if has_postgres_hint else "",
    )

    if not engine:
        engine = "django.db.backends.sqlite3"

    if engine == "django.db.backends.sqlite3":
        sqlite_name = _first_non_empty(os.getenv("DB_NAME"))
        return {
            "ENGINE": engine,
            "NAME": sqlite_name or (BASE_DIR / "db.sqlite3"),
        }

    name = _first_non_empty(
        parsed_url.get("NAME"),
        os.getenv("POSTGRES_DATABASE"),
        os.getenv("PGDATABASE"),
        os.getenv("DB_NAME"),
    )
    user = _first_non_empty(
        parsed_url.get("USER"),
        os.getenv("POSTGRES_USER"),
        os.getenv("PGUSER"),
        os.getenv("DB_USER"),
    )
    password = _first_non_empty(
        parsed_url.get("PASSWORD"),
        os.getenv("POSTGRES_PASSWORD"),
        os.getenv("PGPASSWORD"),
        os.getenv("DB_PASSWORD"),
    )
    host = _first_non_empty(
        parsed_url.get("HOST"),
        os.getenv("POSTGRES_HOST"),
        os.getenv("PGHOST"),
        os.getenv("PGHOST_UNPOOLED"),
        os.getenv("DB_HOST"),
    )
    port = _first_non_empty(
        parsed_url.get("PORT"),
        os.getenv("POSTGRES_PORT"),
        os.getenv("PGPORT"),
        os.getenv("DB_PORT"),
        "5432",
    )

    sslmode = _first_non_empty(
        parsed_url.get("SSLMODE"),
        os.getenv("PGSSLMODE"),
        os.getenv("DB_SSLMODE"),
        "require",
    )
    channel_binding = _first_non_empty(
        parsed_url.get("CHANNEL_BINDING"),
        os.getenv("PGCHANNELBINDING"),
        os.getenv("DB_CHANNEL_BINDING"),
    )
    connect_timeout_raw = _first_non_empty(
        os.getenv("DB_CONNECT_TIMEOUT"),
        parsed_url.get("CONNECT_TIMEOUT"),
        "15",
    )
    conn_max_age_raw = _first_non_empty(os.getenv("DB_CONN_MAX_AGE"), "60")

    db_settings = {
        "ENGINE": engine,
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": port,
    }

    options = {}
    if sslmode:
        options["sslmode"] = sslmode
    if channel_binding:
        options["channel_binding"] = channel_binding

    try:
        connect_timeout = int(connect_timeout_raw)
    except (TypeError, ValueError):
        connect_timeout = 15
    options["connect_timeout"] = max(1, connect_timeout)

    if options:
        db_settings["OPTIONS"] = options

    try:
        conn_max_age = int(conn_max_age_raw)
    except (TypeError, ValueError):
        conn_max_age = 60
    db_settings["CONN_MAX_AGE"] = max(0, conn_max_age)

    return db_settings


ALLOWED_HOSTS = _split_csv_env(
    "DJANGO_ALLOWED_HOSTS",
    [
        "192.168.100.167",
        "localhost",
        "127.0.0.1",
        ".vercel.app",
        ".trycloudflare.com",
        ".ngrok-free.app",
        ".ngrok.app",
        ".loca.lt",
    ],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'phonenumber_field',
    'schoolapp',
    'testapp',
    'nazoratapp',
    'rest_framework.authtoken',
    'import_export',
    'django_seed',
    'drf_spectacular',
    'corsheaders',
    'rest_framework_simplejwt',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'school_project.middleware.ApiExceptionToJsonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add these to your Django settings.py
CSRF_TRUSTED_ORIGINS = _split_csv_env(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "https://*.trycloudflare.com",
        "https://*.ngrok-free.app",
        "https://*.ngrok.app",
        "https://*.loca.lt",
    ],
)


# Make sure you have these CORS settings
CORS_ALLOWED_ORIGINS = _split_csv_env(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
)

# For development only
CORS_ALLOW_ALL_ORIGINS = os.getenv(
    "DJANGO_CORS_ALLOW_ALL_ORIGINS",
    "true" if DEBUG else "false",
).lower() == "true"
CORS_ALLOW_CREDENTIALS = True


# Important: Configure CSRF for cross-origin requests
CSRF_COOKIE_SECURE = os.getenv(
    "DJANGO_CSRF_COOKIE_SECURE",
    "false" if DEBUG else "true",
).lower() == "true"
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests
CSRF_USE_SESSIONS = False  # Use cookie instead of session
CSRF_COOKIE_NAME = 'csrftoken'

# Session settings (if using session authentication)
SESSION_COOKIE_SECURE = os.getenv(
    "DJANGO_SESSION_COOKIE_SECURE",
    "false" if DEBUG else "true",
).lower() == "true"
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'

ROOT_URLCONF = 'school_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'schoolapp.context_processors.menu_links',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": _build_database_settings()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/redirect/'
LOGIN_URL = 'school/login/'
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
    
SPECTACULAR_SETTINGS = {
    'TITLE': 'My School API',
    'DESCRIPTION': 'API documentation for test, users, tasks, etc.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
