# Generated by Django 5.2.3 on 2025-08-15 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolapp', '0014_rename_max_grade_task_max_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nazorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('task', 'Task'), ('test', 'Test')], max_length=10)),
                ('source_id', models.PositiveIntegerField()),
                ('max_score', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='NazoratResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.FloatField(default=0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nazorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nazoratapp.nazorat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
            ],
            options={
                'unique_together': {('nazorat', 'student')},
            },
        ),
    ]
