# Generated by Django 5.2.4 on 2025-07-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_remove_group_teacher_remove_task_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
        migrations.AddField(
            model_name='task',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.enrollment'),
        ),
    ]
