# Generated by Django 5.2.4 on 2025-08-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_remove_task_course_task_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.course'),
        ),
    ]
