# Generated by Django 5.2.4 on 2025-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_remove_task_enrollment_task_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_course',
            field=models.BooleanField(default=False, help_text='Is this task assigned to a course?'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to_student',
            field=models.BooleanField(default=False, help_text='Is this task assigned to a specific student?'),
        ),
    ]
