# Generated by Django 5.2.4 on 2025-08-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_task_assigned_to_course_task_assigned_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_student',
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
