# Generated by Django 5.2.4 on 2025-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_remove_task_max_grade_remove_task_updated_at_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.AddField(
            model_name='task',
            name='max_grade',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
