# Generated by Django 5.2.4 on 2025-08-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_remove_group_teacher_remove_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
    ]
