# Generated by Django 5.2.4 on 2025-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_remove_task_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_date',
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.JSONField(help_text='e.g. {"days": [0, 2, 4], "time": "10:00 - 11:30"}'),
        ),
    ]
