# Generated by Django 5.2.4 on 2025-08-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_remove_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
    ]
