# Generated by Django 5.2.4 on 2025-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_remove_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.JSONField(default=1, help_text='e.g. {"days": [0, 2, 4], "time": "10:00 - 11:30"}'),
            preserve_default=False,
        ),
    ]
