# Generated by Django 5.2.3 on 2025-08-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_course_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='max_grade',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='grade',
            new_name='score',
        ),
    ]
