# Generated by Django 5.2.4 on 2025-08-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_course_schedule'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='testid',
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='question',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='created_by',
            new_name='teacherid',
        ),
        migrations.RenameField(
            model_name='testattempt',
            old_name='student',
            new_name='studentid',
        ),
        migrations.RenameField(
            model_name='testattempt',
            old_name='test',
            new_name='testid',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='mark',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='scored_mark',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('attemt_count', models.PositiveIntegerField(default=3)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tests', to='schoolapp.course')),
                ('test_attempt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tests', to='testapp.testattempt')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tests', to='testapp.test')),
            ],
        ),
    ]
