# Generated by Django 5.2.4 on 2025-08-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_type_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='testapp.question'),
        ),
    ]
