# Generated by Django 5.2.3 on 2025-08-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_course_schedule'),
        ('testapp', '0004_alter_answer_questionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='attempt',
            new_name='attemptid',
        ),
        migrations.RemoveField(
            model_name='coursetest',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='testid',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='courseid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='schoolapp.course'),
            preserve_default=False,
        ),
    ]
