# Generated by Django 5.2.3 on 2025-08-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_attempt_studentanswer_attemptid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='testid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testapp.test'),
            preserve_default=False,
        ),
    ]
