# Generated by Django 5.2.3 on 2025-08-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_course_schedule'),
        ('testapp', '0006_testattempt_testid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='courseid',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='Enrollmentid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='schoolapp.enrollment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EnrollmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('attemt_count', models.PositiveIntegerField(default=3)),
                ('Enrollmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enrollment_tests', to='schoolapp.enrollment')),
                ('test_attempt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enrollment_tests', to='testapp.testattempt')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enrollment_tests', to='testapp.test')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseTest',
        ),
    ]
