# Generated by Django 5.2.3 on 2025-08-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_testattempt_courseid_testattempt_enrollmentid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmenttest',
            old_name='Enrollmentid',
            new_name='enrollment',
        ),
    ]
