# Generated by Django 5.2.3 on 2025-08-08 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_course_schedule'),
        ('testapp', '0008_rename_enrollmentid_enrollmenttest_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questionid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='enrollmenttest',
            old_name='attemt_count',
            new_name='attempt_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='testid',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='attemptid',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='studentanswer',
            old_name='questionid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='teacherid',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='testattempt',
            old_name='Enrollmentid',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='testattempt',
            old_name='studentid',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='testattempt',
            old_name='testid',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='enrollmenttest',
            name='test_attempt_id',
        ),
        migrations.RemoveField(
            model_name='enrollmenttest',
            name='testid',
        ),
        migrations.AddField(
            model_name='enrollmenttest',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tests', to='testapp.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollmenttest',
            name='test_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tests', to='testapp.testattempt'),
        ),
        migrations.AlterField(
            model_name='enrollmenttest',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tests', to='schoolapp.enrollment'),
        ),
    ]
