# Generated by Django 5.2.3 on 2025-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_rename_questionid_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='mark',
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=1.1),
        ),
    ]
