# Generated by Django 5.2.3 on 2025-08-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_remove_enrollmenttest_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmenttest',
            name='test_attempt',
        ),
    ]
