# Generated by Django 5.2.3 on 2025-08-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_course_schedule'),
        ('testapp', '0013_remove_enrollmenttest_test_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenttest',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tests', to='schoolapp.student'),
            preserve_default=False,
        ),
    ]
