# Generated by Django 5.2.3 on 2025-08-11 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_course_schedule'),
        ('testapp', '0014_enrollmenttest_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='schoolapp.course'),
            preserve_default=False,
        ),
    ]
