# Generated by Django 5.2.3 on 2025-08-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_remove_testattempt_enrollment_testattempt_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='course',
        ),
    ]
