# Generated by Django 5.2.3 on 2025-08-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_testattempt_percentage_testattempt_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmenttest',
            name='student',
        ),
    ]
